import { ProductModel } from './product.model';

export const responseMock: ProductModel[] = [
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://cdn.dummyjson.com/product-images/1/thumbnail.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://cdn.dummyjson.com/product-images/2/thumbnail.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://cdn.dummyjson.com/product-images/3/thumbnail.jpg',
  },
  {
    id: 1,
    title: `Samsung Universe 9`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
  {
    id: 1,
    title: `Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops`,
    description: `Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday`,
    price: 109.95,
    rating: 4.09,
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
];
